# Generated by Django 2.0.6 on 2018-08-30 01:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180829_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_num', models.IntegerField(default=1)),
                ('detail', models.CharField(max_length=128)),
                ('importance', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'the detail step of Operation Questions',
            },
        ),
        migrations.AddField(
            model_name='examrecord',
            name='assessor',
            field=models.CharField(default='sys_root', max_length=32, verbose_name='assessor'),
        ),
        migrations.AlterField(
            model_name='question',
            name='que_type',
            field=models.CharField(choices=[(1, 'Choice question 选择题'), (2, 'Completion 填空题'), (3, 'Judgment problem 判断题'), (4, 'Operation Questions 操作题')], max_length=1),
        ),
        migrations.AddField(
            model_name='step',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app01.Question'),
        ),
    ]
