# Generated by Django 2.0.6 on 2018-08-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='info_type_name',
            field=models.CharField(default='Commonly Use Words Menu', max_length=32),
        ),
        migrations.AlterField(
            model_name='information',
            name='info_type',
            field=models.IntegerField(choices=[(1, 'Commonly Use Words'), (2, 'Commonly Use Words Menu')], default=2),
        ),
    ]
